name: 'Arborist'
description: 'Branch protection and reconstruction for GitHub Classroom assignments'
inputs:
  branches:
    description: 'Branches to protect provided as an array'
    required: true
    default: '["main", "feedback"]'
  min-approvals:
    description: 'Minimum number of approvals for branches'
    required: true
    default: 1
    type: number
  team-roles:
    description: 'Key-value pairs of teams and applicable repository roles'
    required: false
    default: '{}'
    type: string
  enforce-admins:
    description: 'Allows named accounts to bypass the branch protection'
    required: true
    default: false
    type: boolean
  force-protect:
    description: 'Forces branch protection regardless of assignment/template status'
    required: false
    default: false
    type: boolean
runs:
  using: 'node20'
  main: 'dist/index.js'
